# This is an example configuration file for training a model using the specified dataset, optimizer, and scheduler.
# You can modify the parameters as needed and add more
# to use this file, run the training script with:
# python3 -m src.train --config-path ../user_configs --config-name my_config from the project root directory.
# Not described parameters will take default values from the data classes in src/config.py

dataset: wine_quality
optimizer: adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001
criterion: cross_entropy
batch_size: 64
scheduler:
  name: steplr
  step_size: 5
init_xavier: false